### ISSUE TITLE
Tasks for the week of 2nd March

### ISSUE THREAD

**Issue by QuicksandDesignStudio** [QuicksandDesignStudio/junglesounds#1]
- [x] Add buttons to Audio Classifier web-app to make mobile compliant @QuicksandDesignStudio 
- [x] Add recorded time as a parameter for the sample @thejeshgn 
- [x] Add pages to Get all Samples - right now can get only 10 @thejeshgn 
- [x] Add pages to Get all Classifications - right now can get only 10 @thejeshgn 
- [x] Integrate Audio Classifier Client Side Code within the API-APP @thejeshgn 
- [x] Integrate API end-points between API-APP and Audio Classifier Client Side code @QuicksandDesignStudio 
- [x] Delete Audio Classifier Repo after integration of Classifier Client Side with API-APP @QuicksandDesignStudio 
- [ ] Remove uploaded wave data from git repo @thejeshgn 
- [ ] Migrate API-APP with Audio Classifier Client Side Code to AWS / GCC @thejeshgn 
- [x] Write batch script to batch transfer samples to AWS S3 (or GCC equivalent) @QuicksandDesignStudio 
- [x] Upload samples to AWS S3 (or GCC equivalent) @QuicksandDesignStudio 
- [ ] Release and distribute Audio Classifier web-app @QuicksandDesignStudio

**Comment by thejeshgn** [comment]
I have added the classifier to the API flask app. 

 Small change in the API end point. Now it will be at 

`http://localhost:5000/api/<rest>
`

**Comment by QuicksandDesignStudio** [comment]
- Noted on the API change
- Added index.html and readme to the static folder in app-api 
- deleted Audio Classifier repo

**Comment by thejeshgn** [comment]
Wave files wont be served from static folder

It will be served from `http://localhost:5000/download/1582709239.1903648.wav`

**Comment by QuicksandDesignStudio** [comment]
Yes sure, I have copied it to the static folder now to do some UI related things (for mobile compatibility before I integrate the API). Will remove

**Comment by thejeshgn** [comment]
Done pagination. Updated documentation.

**Comment by QuicksandDesignStudio** [comment]
Done API integration

**Comment by QuicksandDesignStudio** [comment]
Thej we should remove the audio data from the repo, now all the audio clips are being committed to the repo. I will let you do it so I don't break anything. Added to the issue

**Comment by thejeshgn** [comment]
Will remove and add it to .gitignore

**Comment by QuicksandDesignStudio** [comment]
only three tasks remaining!

**Comment by QuicksandDesignStudio** [comment]
Closing this and adding pending items to another issue for this week @thejeshgn
